- name: Create kalite service(s) and support scripts
  template: backup=yes
            src={{ item.src }}
            dest={{ item.dest }}
            owner=root
            group=root
            mode={{ item.mode }}
  with_items:
    - { src: 'kalite-serve.service.j2', dest: '/etc/systemd/system/kalite-serve.service', mode: '0655'}
    - { src: 'kalite-cron.service.j2', dest: '/etc/systemd/system/kalite-cron.service', mode: '0655'}
    - { src: 'xsce_cronservectl.sh.j2', dest: '{{ kalite_root }}/scripts/xsce_cronservectl.sh', mode: '0755'}

- name: Disable kalite server
  service: name=kalite-serve
           enabled=no
           state=stopped
  when: not kalite_enabled

- name: Enable kalite server
  service: name=kalite-serve
           enabled=yes
           state=started
  async: 120
  poll: 5
  when: kalite_enabled

- name: Disable kalite cron server
  service: name=kalite-cron
           enabled=no
           state=stopped
  when: not kalite_cron_enabled

- name: Enable kalite cron server
  service: name=kalite-cron
           enabled=yes
           state=started
  when: kalite_cron_enabled
