- name: Create xsce-kalite user and password
  user: name={{ kalite_user }}
        password={{ kalite_password_hash }}
        update_password=on_create

- name: Create kalite_root directory
  file: path={{ kalite_root }}
        owner=root
        group=root
        mode=0755
        state=directory

- name: Copy the kalite repo into place
  command: "rsync -at {{ downloads_dir }}/ka-lite/ {{ kalite_root }}"

- name: Make kalite_user owner
  file: path={{ kalite_root }}
        owner={{ kalite_user }}
        group={{ kalite_user }}
        recurse=yes
        state=directory

# local_settings is deprecated
- name: Copy local_settings file
  template: src=local_settings.py.j2
            dest="{{ kalite_root }}/kalite/local_settings.py"
            owner={{ kalite_user }}
            group={{ kalite_user }}
            mode=644

- name: Run the install using kalite manage
  command: "/usr/bin/su {{ kalite_user }} -c '{{ kalite_root }}/bin/kalite manage setup --username={{ kalite_user }} --password={{ kalite_password }} --noinput'"
  async: 300
  poll: 10

- name: Finish install by running kalite start
  command: "/usr/bin/su {{ kalite_user }} -c '{{ kalite_root }}/bin/kalite start'"
  async: 300
  poll: 10

- name: Stop kalite server started in previous step because we use systemd
  command: "/usr/bin/su {{ kalite_user }} -c '{{ kalite_root }}/bin/kalite stop'"
