# dhcpd service is restarted with NM dispatcher.d script
- name: Stop named service
  service: name=named
           state=stopped
  when: not named_enabled

- name: Start named service
  service: name=named
           state=started
  when: named_enabled

- name: Restart dansguardian
  service: name=dansguardian
           state=restarted
  when: dansguardian_enabled

# Squid get re-loaded with dispatcher.d
- name: Restart squid service
  service: name=squid
           state=started
  when: squid_enabled

- name: Restart wondershaper service
  service: name=wondershaper
            state=restarted
  when: wondershaper_enabled

- name: Restart avahi service
  service: name=avahi-daemon
           state=restarted

- name: Use larger hammer to disable firewalld (2 symbolic links involved)
  shell: "systemctl disable firewalld.service"

- name: Run iptables
  command: /usr/bin/xs-gen-iptables

- name: Restart iptables service
  service: name=iptables
           state=restarted
  ignore_errors: True
